"""initial revision

Revision ID: 22670a333aab
Revises: 
Create Date: 2016-06-18 22:33:27.624068

"""

# revision identifiers, used by Alembic.
revision = '22670a333aab'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('services',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sv_id', sa.String(), nullable=False),
    sa.Column('sv_name', sa.Enum('fb', 'gh', name='svc_type'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sv_name', 'user_id'),
    sa.UniqueConstraint('sv_id', 'sv_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('users')
    ### end Alembic commands ###
